---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "connectivity_computematrix"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "connectivity":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: 

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  
  - input:
      type: file
      description: 
      pattern: 

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  
  - output:
      type: file
      description: 
      pattern: 

authors:
  - "@ThoumyreStanislas"
maintainers:
  - "@ThoumyreStanislas"
